### PR TITLE
Dont run on every run

### PR DESCRIPTION
**Pull request by BillWeiss**
I think this does the same this as the replaced bit intended, but it wasn't working for me.  I'm running boxen a lot while I figure it out and I was annoyed by the continuous downloads :)

### CODE REVIEW

**Comment by BillWeiss** [comment]
I had to change the spec on both of my PRs (#3 being the other), which will make merging them a bit headachey.  Sorry :(  If you'd prefer I could make one PR that contains both.  They don't logically conflict, it's just a bit too close together for git's comfort.

**Comment by hwhelchel** [comment]
:+1: please merge this. It will speed up our boxen deploys

**Comment by BillWeiss** [comment]
Thanks for the reminder!  I'm on it.

**Comment by BillWeiss** [comment]
Oh, this isn't my fork :(  I'm not on it, though I'd love to see it merged.

**Comment by hwhelchel** [comment]
@BillWeiss no worries! @erivello ping

**Comment by hwhelchel** [comment]
@erivello how can we reference this commit in the boxen puppetfile? thanks for merging it!

**Comment by erivello** [comment]
Hi everybody, what can i do?

**Pull request merged**
